config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users do
    resources :messages, only: [:index, :create, :destroy]
    collection do
      get :subject_select
    end
    member do
      get :followings
      get :followers
      get :favorites
    end
  end
  
  # get 'users/subject_select', as: 'subject_select'
  
  resources :posts, only: [:index, :show, :create, :destroy, :update, :edit] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :receive_user, class_name: 'User'
  
  validates :content, presence: true, length: { maximum: 300 }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user_logged_in
  
  def index
    @user = User.find(params[:user_id])
    send_ids = current_user.messages.where(receive_user_id: @user.id).pluck(:id)
    receive_ids = @user.messages.where(receive_user_id: current_user.id).pluck(:id)
    @messages = Message.where(id: send_ids + receive_ids).order(created_at: :asc)
    @message = Message.new
  end

  def create
    @user = User.find(params[:user_id])
    @message = current_user.messages.build(message_params)
    @message.receive_user_id = @user.id
    if @message.save
      flash[:success] = 'メッセージを送信しました。'
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = 'メッセージを送信できませんでした。'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def message_params
    params.require(:message).permit(:content)
  end
end

app/views/messages/_dm_button.html.erb
<% unless current_user == user %>  
      <%= link_to 'メッセージ', user_messages_path(user), class: "btn btn-info btn-block" %>
<% end %>

app/views/messages/_form.html.erb
<%= form_for message, :url => {:action => :create} do |f| %>
  <%= f.text_field :content %>
  <br>
  <%= f.submit '送信' %>
<% end %>

app/views/messages/index.html.erb
<h2>メッセージ一覧</h2>
<% user = User.find_by(id: @message.receive_user_id) %>
<% @messages.each do |message| %>
  <div>
    <div class="media-left">
        <% if message.user.image? %>
　　      <%= image_tag message.user.image.thumb.url, { size: 50 } %>
　      <% else %>
          <img class="media-object img-circle" src="<%= gravatar_url(message.user, { size: 50 }) %>" alt="">
        <% end %>
    </div>
    <div class="media-body">
        <div>
          <%= link_to message.user.nickname, user_path(message.user) %> <span class="text-muted">posted at <%= message.created_at %></span>
        </div>
        <div>
          <%= message.content %><br>
          <% if current_user == message.user %>
            <%= link_to "削除", user_message_path(current_user, message), method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
          <% end %>
        </div>
    </div>
    <hr>
  </div>
<% end %>

<h2>メッセージ</h2>
<%= render 'messages/form', message: @message %>
<%= link_to "ホームへ戻る", user_path(current_user) %>