config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users do
    resources :messages, only: [:index, :create, :destroy]
    collection do
      get :subject_select
    end
    member do
      get :followings
      get :followers
      get :favorites
    end
  end
  
  # get 'users/subject_select', as: 'subject_select'
  
  resources :posts, only: [:index, :show, :create, :destroy, :update, :edit] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :grade
  belongs_to :department
  belongs_to :subject
  
  before_save { self.email.downcase! }
  validates :department, presence: true
  validates :subject, presence: true
  validates :nickname, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :posts, dependent: :destroy
  
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  
  has_many :comments, dependent: :destroy
  
  has_many :messages, dependent: :destroy
  has_many :sent_messages, through: :messages, source: :receive_user 
  has_many :reverses_of_message, class_name: 'Message', foreign_key: 'receive_user_id', dependent: :destroy
  has_many :received_messages, through: :reverses_of_message, source: :user
  
  mount_uploader :image, ImageUploader
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def feed_posts
    Post.where(user_id: self.following_ids + [self.id])
  end
  
  def favorite(post)
    self.favorites.find_or_create_by(post_id: post.id)
  end
  
  def unfavorite(post)
    favorite = self.favorites.find_by(post_id: post.id)
    favorite.destroy if favorite
  end
  
  def favorite?(post)
    self.favorite_posts.include?(post)
  end
  
  def message
    unless self == other_user
      self.messages.create(receive_user_id: other_user.id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit, :destroy, :followings, :followers, :favorites]
  before_action :correct_user, only: [:edit, :update]
  
  def index
    @users = User.all.page(params[:page])
    @user = User.find(session[:user_id])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order('created_at DESC').page(params[:page])
    counts(@user)
  end
  
  def edit
  end
  
  def update
    @user = User.find(params[:id])
    if current_user == @user
      if @user.update(user_params)
        flash[:success] = 'ユーザー情報を編集しました。'
        redirect_to @user
      else
        flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
        render :edit
      end
    else
      redirect_to root_url
    end
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = '退会しました。'
    redirect_to root_path
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  def favorites
    @user = User.find(params[:id])
    @posts = @user.favorite_posts.page(params[:page])
    counts(@user)
  end
  
  def subject_select
    @subjects = params[:user_department_id] ? Subject.where(department_id: params[:user_department_id]) : []
  end
  
  private
  
  def user_params
    params.require(:user).permit(:grade_id, :department_id, :subject_id, :nickname, :email, :password, :password_confirmation, :image, :image_cache)
  end
  
  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user == @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <% if user.image? %>
　　        <%= image_tag user.image.thumb.url, { size: 50 } %>
　        <% else %>
　　      <!--%= image_tag 'noimage.gif' %-->
            <img class="media-object img-circle" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
          <% end %>
        </div>
        <div class="media-body">
          <div>
            <%= link_to user.nickname, user_path(user) %>
          </div>
          <div>
            <p>
              <%= user.grade.year %>/
              <%= user.department.name %>/
              <%= user.subject.name %>
            </p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>編集ページ</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
        <%= f.label :image, '画像' %>
　      <%= image_tag @user.image.thumb.url if @user.image? %>
　      <%= f.file_field :image %>
　      <%= f.hidden_field :image_cache %>
    
      <div class="form-group">
        <%= f.label :grade_id, '学年' %>
        <%= f.collection_select :grade_id, Grade.all, :id, :year, {:prompt => "選択してください"}, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :department_id, '学部' %>
        <%= f.collection_select :department_id, Department.all, :id, :name, {:prompt => "選択してください "}, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :subject_id, '学科' %>
        <span id='subject_result'>
          <%= collection_select :user, :subject_id, Subject.where(id: @user.subject_id), :id, :name, {selected: @user.subject_id, :prompt => "選択してください"}, class: 'form-control' %>
        </span>
      </div>

      <div class="form-group">
        <%= f.label :nickname, 'ニックネーム' %>
        <%= f.text_field :nickname, :placeholder => "例）タロウ", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, :placeholder => "例）taro1234@yahoo.co.jp", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード（確認用）' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録する', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

<script>
  $('#user_department_id').change(function() {
    console.log("hello");
    $.ajax({
      url: '<%= subject_select_users_path %>',
      type: 'get',
      data:{
        user_department_id: $('#user_department_id').val()
      }
    })
  });
</script>

app/views/users/favorites.html.erb
<div class="row">
  <div class="col-sm-4 col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.nickname %></h3>
        <h4 class="panel-title">
          <%= @user.grade.year %>
          <%= @user.department.name %>
          <%= @user.subject.name %>
        </h4>
      </div>
      <div class="panel-body">
        <% if @user.image? %>
　　      <%= image_tag @user.image.thumb.url %>
　      <% else %>
　　      <!--%= image_tag 'noimage.gif' %-->
          <img class="media-object img-circle img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
        <% end %>
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
    <%= render 'posts/post_button', user: @user %>
    <%= render 'messages/dm_button', user: @user %>
  </div>
  <div class="col-sm-8 col-md-8 between">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>過去の投稿 <span class="badge"><%= @count_posts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>フォロー <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>フォロワー <span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(favorites_user_path(@user)) %>"><%= link_to favorites_user_path(@user) do %>お気に入り一覧 <span class="badge"><%= @count_favorites %></span><% end %></li>
    </ul>
    
    <%= render 'posts/posts', posts: @posts %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="row">
  <div class="col-sm-4 col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.nickname %></h3>
        <h4 class="panel-title">
          <%= @user.grade.year %>
          <%= @user.department.name %>
          <%= @user.subject.name %>
        </h4>
      </div>
      <div class="panel-body">
        <% if @user.image? %>
　　      <%= image_tag @user.image.thumb.url %>
　      <% else %>
　　      <!--%= image_tag 'noimage.gif' %-->
          <img class="media-object img-circle img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
        <% end %>
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
    <%= render 'posts/post_button', user: @user %>
    <%= render 'messages/dm_button', user: @user %>
  </div>
  <div class="col-sm-8 col-md-8 between">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>過去の投稿 <span class="badge"><%= @count_posts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>フォロー <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>フォロワー <span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(favorites_user_path(@user)) %>"><%= link_to favorites_user_path(@user) do %>お気に入り一覧 <span class="badge"><%= @count_favorites %></span><% end %></li>
    </ul>
    <%= render 'users', users: @followers %>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <div class="col-sm-4 col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.nickname %></h3>
        <h4 class="panel-title">
          <%= @user.grade.year %>
          <%= @user.department.name %>
          <%= @user.subject.name %>
        </h4>
      </div>
      <div class="panel-body">
        <% if @user.image? %>
　　      <%= image_tag @user.image.thumb.url %>
　      <% else %>
　　      <!--%= image_tag 'noimage.gif' %-->
          <img class="media-object img-circle img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
        <% end %>
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
    <%= render 'posts/post_button', user: @user %>
    <%= render 'messages/dm_button', user: @user %>
  </div>
  <div class="col-sm-8 col-md-8 between">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>過去の投稿 <span class="badge"><%= @count_posts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>フォロー <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>フォロワー <span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(favorites_user_path(@user)) %>"><%= link_to favorites_user_path(@user) do %>お気に入り一覧 <span class="badge"><%= @count_favorites %></span><% end %></li>
    </ul>
    <%= render 'users', users: @followings %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

　　    <%= f.label :image, '画像' %>
　　    <%= image_tag @user.image.thumb.url if @user.image? %>
　      <%= f.file_field :image %>
　      <%= f.hidden_field :image_cache %>
      
      <div class="form-group">
        <%= f.label :grade_id, '学年' %>
        <%= f.collection_select :grade_id, Grade.all, :id, :year, {:prompt => "選択してください"}, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :department_id, '学部' %>
        <%= f.collection_select :department_id, Department.all, :id, :name, {:prompt => "選択してください "}, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :subject_id, '学科' %>
        <span id='subject_result'>
          <%= collection_select :user, :subject_id, [], :id, :name, {:prompt => "選択してください"}, class: 'form-control' %>
        </span>
      </div>

      <div class="form-group">
        <%= f.label :nickname, 'ニックネーム' %>
        <%= f.text_field :nickname, :placeholder => "例）タロウ", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, :placeholder => "例）taro1234@yahoo.co.jp", class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード（確認用）' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録する', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

<script>
  $('#user_department_id').change(function() {
    console.log("hello");
    $.ajax({
      url: '<%= subject_select_users_path %>',
      type: 'get',
      data:{
        user_department_id: $('#user_department_id').val()
      }
    })
  });
</script>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-4 col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.nickname %></h3>
        <h4 class="panel-title">
          <%= @user.grade.year %>
          <%= @user.department.name %>
          <%= @user.subject.name %>
        </h4>
      </div>
      <div class="panel-body">
        <% if @user.image? %>
　　      <%= image_tag @user.image.thumb.url %>
　      <% else %>
　　      <!--%= image_tag 'noimage.gif' %-->
          <img class="media-object img-circle img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
        <% end %>  
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
    <%= render 'posts/post_button', user: @user %>
    <%= render 'messages/dm_button', user: @user %>
  </div>
  <div class="col-sm-8 col-md-8 between">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>過去の投稿 <span class="badge"><%= @count_posts %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>フォロー <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>フォロワー <span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(favorites_user_path(@user)) %>"><%= link_to favorites_user_path(@user) do %>お気に入り一覧 <span class="badge"><%= @count_favorites %></span><% end %></li>
    </ul>
    <%= render 'posts/posts', posts: @posts %>
  </div>
</div>

app/views/users/subject_select.js.erb
$("#subject_result").html('<%=j collection_select :user, :subject_id, @subjects, :id, :name, {:prompt => "選択してください"}, class: 'form-control' %>');q