config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users do
    resources :messages, only: [:index, :create, :destroy]
    collection do
      get :subject_select
    end
    member do
      get :followings
      get :followers
      get :favorites
    end
  end
  
  # get 'users/subject_select', as: 'subject_select'
  
  resources :posts, only: [:index, :show, :create, :destroy, :update, :edit] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :lesson
  belongs_to :teacher
  
  validates :lesson_evaluation, presence: true
  validates :lesson_level, presence: true
  validates :text_necessity, presence: true
  validates :attendance, presence: true
  validates :additional_explanation, length: { maximum: 300 }
  
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy, :update, :edit]
  before_action :set_params, only: [:show, :create, :edit]
  
  def index
    @posts = Post.all.order('created_at DESC').page(params[:page])
    @user = User.find(session[:user_id])
  end
  
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = '投稿しました。'
      redirect_to posts_path
    else
      @posts = current_user.feed_posts.order('created_at DESC').page(params[:page])
      flash.now[:danger] = '投稿に失敗しました。'
      render 'toppages/index'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = '投稿を削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    
    if @post.update(post_params)
      flash[:success] = '投稿は正常に更新されました。'
      redirect_to root_url
    else
      flash.now[:danger] = '投稿は更新されませんでした。'
      render :edit
    end
  end
  
  private
  
  def set_params
    @user = User.find(session[:user_id])
  end
  
  def post_params
    params.require(:post).permit(:lesson_id, :teacher_id, :lesson_evaluation, :lesson_level, :text_necessity, :attendance, :additional_explanation)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
        <div class="form-group">
          <%= f.label :lesson_id, '授業名' %>
          <%= f.collection_select :lesson_id, Lesson.all, :id, :name, {:include_blank => '選択してください'}, {class: "searchable"} %>
        </div>
        
        <div class="form-group">
          <%= f.label :teacher_id, '先生の名前' %>
          <%= f.collection_select :teacher_id, Teacher.all, :id, :name, {:include_blank => '選択してください'}, {class: "searchable"} %>
        </div>
        
        <div class="form-group">
          <%= f.label :lesson_evaluation, '授業評価' %>
          <%= f.radio_button :lesson_evaluation, '良い' %>
          <%= f.label :lesson_evaluation, '良い' %>
          <%= f.radio_button :lesson_evaluation, '普通' %>
          <%= f.label :lesson_evaluation, '普通' %>
          <%= f.radio_button :lesson_evaluation, '悪い' %>
          <%= f.label :lesson_evaluation, '悪い' %>
        </div>
        
        <div class="form-group">
          <%= f.label :lesson_level, '授業難易度' %>
          <%= f.radio_button :lesson_level, '簡単' %>
          <%= f.label :lesson_level, '簡単' %>
          <%= f.radio_button :lesson_level, '普通' %>
          <%= f.label :lesson_level, '普通' %>
          <%= f.radio_button :lesson_level, '難しい' %>
          <%= f.label :lesson_level, '難しい' %>
        </div>
        
        <div class="form-group">
          <%= f.label :text_necessity, '教科書の有無' %>
          <%= f.radio_button :text_necessity, '有' %>
          <%= f.label :text_necessity, '有' %>
          <%= f.radio_button :text_necessity, '無' %>
          <%= f.label :text_necessity, '無' %>
        </div>
          
        <div class="form-group">
          <%= f.label :attendance, '出席の有無' %>
          <%= f.radio_button :attendance, '有' %>
          <%= f.label :attendance, '有' %>
          <%= f.radio_button :attendance, '無' %>
          <%= f.label :attendance, '無' %>
        </div>
        
        <div class="form-group">  
          <%= f.label :additional_explanation, '補足' %>
          <%= f.text_area :additional_explanation, class: 'form-control', rows: 5 %>
        </div>
        
        <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/posts/_post_button.html.erb
<% if current_user == user %>  
      <%= link_to '投稿する', root_path, class: "btn btn-info btn-block", data: { turbolinks: false } %>
<% end %>

app/views/posts/_posts.html.erb
<ul class="media-list">
  <% posts.each do |post| %>
    <li class="media">
      <div class="media-left">
        <% if post.user.image? %>
　　      <%= image_tag post.user.image.thumb.url, { size: 50 } %>
　      <% else %>
          <img class="media-object img-circle" src="<%= gravatar_url(post.user, { size: 50 }) %>" alt="">
        <% end %>
      </div>
      <div class="media-body">
        <div>
          <%= link_to post.user.nickname, user_path(post.user) %> <span class="text-muted">posted at <%= post.created_at %></span>
        </div>
        <div>
          <p>授業名：<%= post.lesson.name %></p>
          <p>先生の名前：<%= post.teacher.name %></p>
          <p>授業評価：<%= post.lesson_evaluation %></p>
          <p>授業難易度：<%= post.lesson_level %></p>
          <p>教科書の有無：<%= post.text_necessity %></p>
          <p>出席の有無：<%= post.attendance %></p>
          <p>補足：<%= post.additional_explanation %></p>
        </div>
        <div>
          <%= link_to "コメント", post_path(post), class: 'btn btn-info btn-xs' %><span class="badge"><%= post.comments.count %></span>
          <% if current_user == post.user %>
            <%= link_to "編集", edit_post_path(post), class: 'btn btn-primary btn-xs', data: { turbolinks: false } %>
            <%= link_to "削除", post_path(post), method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
          <% else %>
            <%= render 'favorites/favorite_button', post: post %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate posts %>
</ul>

app/views/posts/edit.html.erb
<h2>編集ページ</h2>

<div class="col-md-4">
  <%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<%= render 'posts/posts', posts: @posts %>

app/views/posts/show.html.erb
<h2>投稿詳細ページ</h2>
<ul class="media-list">
  <li class="media">
      <div class="media-left">
        <% if @post.user.image? %>
　　      <%= image_tag @post.user.image.thumb.url, { size: 50 } %>
　      <% else %>
          <img class="media-object img-circle" src="<%= gravatar_url(@post.user, { size: 50 }) %>" alt="">
        <% end %>
      </div>
      <div class="media-body">
        <div>
          <%= link_to @post.user.nickname, user_path(@post.user) %> <span class="text-muted">posted at <%= @post.created_at %></span>
        </div>
        <div>
          <p>授業名：<%= @post.lesson.name %></p>
          <p>先生の名前：<%= @post.teacher.name %></p>
          <p>授業評価：<%= @post.lesson_evaluation %></p>
          <p>授業難易度：<%= @post.lesson_level %></p>
          <p>教科書の有無：<%= @post.text_necessity %></p>
          <p>出席の有無：<%= @post.attendance %></p>
          <p>補足：<%= @post.additional_explanation %></p>
        </div>
      </div>
  </li>
</ul>
<h2>コメント一覧</h2>
<% @post.comments.each do |comment| %>
  <div>
    <div class="media-left">
        <% if comment.user.image? %>
　　      <%= image_tag comment.user.image.thumb.url, { size: 50 } %>
　      <% else %>
          <img class="media-object img-circle" src="<%= gravatar_url(comment.user, { size: 50 }) %>" alt="">
        <% end %>
    </div>
    <div class="media-body">
        <div>
          <%= link_to comment.user.nickname, user_path(comment.user) %> <span class="text-muted">posted at <%= comment.created_at %></span>
        </div>
        <div>
          <%= comment.content %><br>
          <% if current_user == comment.user %>
            <%= link_to "削除", post_comment_path(@post, comment), method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
          <% end %>
        </div>
    </div>
    <hr>
  </div>
<% end %>

<%= form_for [@post, @comment] do |f| %>
  <%= f.text_field :content %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :post_id, :value => @post.id %>
  <br>
  <%= f.submit 'コメントする' %>
<% end %>

<%= link_to "ホームへ戻る", user_path(@post.user) %>