config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users do
    resources :messages, only: [:index, :create, :destroy]
    collection do
      get :subject_select
    end
    member do
      get :followings
      get :followers
      get :favorites
    end
  end
  
  # get 'users/subject_select', as: 'subject_select'
  
  resources :posts, only: [:index, :show, :create, :destroy, :update, :edit] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">© 2018 BKC-CLASS.</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "BKCクラス", posts_path, class: "navbar-brand", data: { turbolinks: false } %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'ユーザー一覧', users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.nickname %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to '新規投稿', root_path, data: { turbolinks: false } %></li>
                <li><%= link_to '投稿一覧', posts_path %></li>
                <li><%= link_to 'プロフィール', user_path(current_user) %></li>
                <li><%= link_to 'ユーザー編集', edit_user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to'ログアウト', logout_path, method: :delete %></li>
                <li><%= link_to'退会する', user_path(current_user), method: :delete, data: { confirm: "You sure?" } %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to'新規登録', signup_path %></li>
            <li><%= link_to'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>BKCクラス</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
        
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>